# Домашнее задание HW01

Работа с NumPy: создание массивов, индексирование, базовые операции.


In [33]:
# Импорт библиотеки NumPy
import numpy as np


## 1. Создание массивов

### 1.1. Создание массива из обычного списка


In [34]:
# Создание одномерного массива из списка
arr1d = np.array([1, 2, 3, 4, 5])
print("Одномерный массив:", arr1d)

# Создание двумерного массива
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерный массив:")
print(arr2d)


Одномерный массив: [1 2 3 4 5]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 1.2. Создание массивов с использованием специальных функций


In [35]:
# Создание массива из нулей
zeros_arr = np.zeros((3, 4))  # матрица 3x4, заполненная нулями
print("Массив из нулей (3x4):")
print(zeros_arr)

# Создание массива из единиц
ones_arr = np.ones((2, 3))  # матрица 2x3, заполненная единицами
print("\nМассив из единиц (2x3):")
print(ones_arr)

# Создание массива с помощью arange
arange_arr = np.arange(0, 10, 2)  # числа от 0 до 10 с шагом 2
print("\nМассив с помощью arange(0, 10, 2):")
print(arange_arr)


Массив из нулей (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Массив из единиц (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Массив с помощью arange(0, 10, 2):
[0 2 4 6 8]


## 2. Атрибуты массивов: shape и dtype


In [36]:
# Демонстрация атрибутов массива
example_arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Массив:")
print(example_arr)
print("\nФорма массива (shape):", example_arr.shape)
print("Тип данных (dtype):", example_arr.dtype)
print("Размерность (ndim):", example_arr.ndim)


Массив:
[[1 2 3]
 [4 5 6]]

Форма массива (shape): (2, 3)
Тип данных (dtype): int64
Размерность (ndim): 2


## 3. Индексирование и срезы

### 3.1. Получение отдельного элемента


In [37]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Исходный массив:")
print(arr)

# Получение отдельного элемента (индексация начинается с 0)
element = arr[1, 2]  # элемент во второй строке, третьем столбце
print(f"\nЭлемент arr[1, 2] = {element}")

# Альтернативный способ для одномерного массива
arr1d = np.array([1, 2, 3, 4, 5])
print(f"\nОдномерный массив: {arr1d}")
print(f"Элемент arr1d[2] = {arr1d[2]}")


Исходный массив:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Элемент arr[1, 2] = 60

Одномерный массив: [1 2 3 4 5]
Элемент arr1d[2] = 3


### 3.2. Извлечение подмассива с помощью срезов


In [38]:
arr = np.array([[10, 20, 30, 40], 
                [50, 60, 70, 80], 
                [90, 100, 110, 120]])
print("Исходный массив:")
print(arr)

subarray = arr[0:2, 1:3]  # первые две строки, столбцы с 1 по 2
print("\nПодмассив arr[0:2, 1:3]:")
print(subarray)

arr1d = np.arange(10)
print(f"\nОдномерный массив: {arr1d}")
print(f"Срез arr1d[2:7]: {arr1d[2:7]}")  # элементы с индекса 2 до 6
print(f"Срез arr1d[:5]: {arr1d[:5]}")  # первые 5 элементов
print(f"Срез arr1d[5:]: {arr1d[5:]}")  # элементы с индекса 5 до конца


Исходный массив:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Подмассив arr[0:2, 1:3]:
[[20 30]
 [60 70]]

Одномерный массив: [0 1 2 3 4 5 6 7 8 9]
Срез arr1d[2:7]: [2 3 4 5 6]
Срез arr1d[:5]: [0 1 2 3 4]
Срез arr1d[5:]: [5 6 7 8 9]


## 4. Векторные операции и базовые статистики

### 4.1. Поэлементные операции над массивами


In [39]:
# Создадим два массива одинаковой формы
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Массив a:", a)
print("Массив b:", b)

# Поэлементное сложение
sum_result = a + b
print(f"\nПоэлементное сложение (a + b): {sum_result}")

# Поэлементное умножение
mult_result = a * b
print(f"Поэлементное умножение (a * b): {mult_result}")

# Операции со скаляром
scalar_add = a + 10
print(f"\nСложение со скаляром (a + 10): {scalar_add}")

scalar_mult = a * 2
print(f"Умножение на скаляр (a * 2): {scalar_mult}")


Массив a: [1 2 3 4 5]
Массив b: [10 20 30 40 50]

Поэлементное сложение (a + b): [11 22 33 44 55]
Поэлементное умножение (a * b): [ 10  40  90 160 250]

Сложение со скаляром (a + 10): [11 12 13 14 15]
Умножение на скаляр (a * 2): [ 2  4  6  8 10]


### 4.2. Базовые статистические функции


In [40]:
# Создадим массив для статистических вычислений
data = np.array([15, 22, 18, 25, 30, 20, 17, 24, 19, 21])
print("Данные:", data)

# Среднее значение
mean_value = np.mean(data)
print(f"\nСреднее значение (mean): {mean_value}")

# Минимальное значение
min_value = np.min(data)
print(f"Минимальное значение (min): {min_value}")

# Максимальное значение
max_value = np.max(data)
print(f"Максимальное значение (max): {max_value}")

# Сумма всех элементов
sum_value = np.sum(data)
print(f"Сумма всех элементов (sum): {sum_value}")

# Стандартное отклонение
std_value = np.std(data)
print(f"Стандартное отклонение (std): {std_value:.2f}")


Данные: [15 22 18 25 30 20 17 24 19 21]

Среднее значение (mean): 21.1
Минимальное значение (min): 15
Максимальное значение (max): 30
Сумма всех элементов (sum): 211
Стандартное отклонение (std): 4.16


### 4.3. Статистики для двумерных массивов


In [41]:
# Двумерный массив
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print("Матрица:")
print(matrix)

# Статистики по всему массиву
print(f"\nСреднее по всему массиву: {np.mean(matrix)}")
print(f"Сумма всех элементов: {np.sum(matrix)}")

# Статистики по осям
print(f"\nСреднее по столбцам (axis=0): {np.mean(matrix, axis=0)}")
print(f"Среднее по строкам (axis=1): {np.mean(matrix, axis=1)}")
print(f"Минимум по столбцам (axis=0): {np.min(matrix, axis=0)}")
print(f"Максимум по строкам (axis=1): {np.max(matrix, axis=1)}")


Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Среднее по всему массиву: 5.0
Сумма всех элементов: 45

Среднее по столбцам (axis=0): [4. 5. 6.]
Среднее по строкам (axis=1): [2. 5. 8.]
Минимум по столбцам (axis=0): [1 2 3]
Максимум по строкам (axis=1): [3 6 9]
